app/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from datetime import datetime
from . import login_manager

@login_manager.user_loader
def load_user(user_id):
  return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    firstname = db.Column(db.String(255))
    lastname = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pass_secure = db.Column(db.String(255))
    posts = db.relationship('Post', backref='user', passive_deletes=True)
    
    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'User {self.username}'

class Post(db.Model):
     __tablename__ = 'posts'

     id = db.Column(db.Integer, primary_key=True)
     text = db.Column(db.Text, nullable=False)
     author = db.Column(db.Integer, db.ForeignKey('users.id',ondelete='CASCADE'), nullable=False)

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()

def create_app(config_name):
  app = Flask(__name__)

  # Creating the app configurations
  app.config.from_object(config_options[config_name])

  # initializing flask extenstions
  bootstrap.init_app(app)
  db.init_app(app)
  login_manager.init_app(app)

  # registering the blueprint
  from .main import main as main_blueprint
  app.register_blueprint(main_blueprint)
  from .auth import auth as auth_blueprint
  app.register_blueprint(auth_blueprint, url_prefix = '/auth')

  # setting config

  return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)
from . import views, error

app/main/views.py
from flask import render_template, request, redirect, url_for, abort,flash
from ..requests import get_blogQuotes
from . import main
from ..models import User
from flask_login import login_required, current_user
from datetime import datetime
from .. import db
from .forms import UpdateProfile

@main.route('/')
def index():
    '''
    '''
    blogQuote =get_blogQuotes()
    title = 'Welcome to My Blog'
    return render_template('index.html',title = title, blogQuote=blogQuote)

@main.route('/home')
@login_required
def home():
    return render_template("home.html" )

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)    

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-black"  role="navigation">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar">
         <span class="navbar-toggler-icon"></span>
      </button> 
       <div class="navbar-collapse collapse" id="navbar">
       <ul class="navbar-nav">
        <li><a class="nav-item nav-link" href="/">Landing page</a></li>
         <li><a class="nav-item nav-link" href="/home">Home</a></li>
       <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_authenticated %}
        <li><a class="nav-item nav-link" href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
        <li><a class="nav-item nav-link" href="{{url_for('auth.logout')}}">Sign out</a></li>
        {% else %}
        <li><a class="nav-item nav-link" href="{{url_for('auth.login')}}">Sign in</a></li>
        {%endif%}
       </ul>
     </div>
        </div>
  </nav>
  {% with messages = get_flashed_messages(with_categories=True) %} {% if messages %} {% for category, message in messages %} {% if category == 'error' %}
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
    {% else %} 
    <div class="alert alert-success alter-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
      </div>
      {% endif %} {% endfor %} {% endif %} {% endwith %} 

     <div class="container">{% block content %} {% endblock %}</div> 

     <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

</body>
</html>

app/templates/create_post.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html' %}

{% block content %}
    <h1>WHOOPS we can't find that page</h1>
{% endblock %}

app/templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% block title %} Welcome to my Blog {% endblock %}

{%block content%}

<div class="home">
  <div class="container">
    <div class="col-md-2"></div>
      <div class="col-md-8">
        <div>
          <h2 style="font-size: 80px; font-family: 'Lobster', cursive;  padding-top: 40px; text-align: center;"> Welcome to Blog</h2>
          <br><br>
          <p>{{blogQuote.quote}}</p>
                
          <p class="text-right"><b>~ {{blogQuote.author}} ~</b> </p>

        </div>
        </div>
        <div class="col-md-2"></div>
    </div>

</div>
{%endblock%}

app/templates/post_div.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}

app/templates/posts.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}

    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
{% endif %}
  </div>
</div>
</div>
{% endblock %} 

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}